import type { SidebarConfig } from '@vuepress/theme-default'

export const sidebarZh: SidebarConfig = {
  '/zh/DShanMCU_RA6M5/object_oriented_module_programming_method_in_ARM_embedded_system/':
    [
      {
        text: 'ARM嵌入式系统中面向对象的模块编程方法',
        collapsible: true,
        children: [
          '/zh/DShanMCU_RA6M5/object_oriented_module_programming_method_in_ARM_embedded_system/README.md',
          '/zh/DShanMCU_RA6M5/object_oriented_module_programming_method_in_ARM_embedded_system/chapter1.md',
          '/zh/DShanMCU_RA6M5/object_oriented_module_programming_method_in_ARM_embedded_system/chapter2.md',
          '/zh/DShanMCU_RA6M5/object_oriented_module_programming_method_in_ARM_embedded_system/chapter3.md',
          '/zh/DShanMCU_RA6M5/object_oriented_module_programming_method_in_ARM_embedded_system/chapter4.md',
          '/zh/DShanMCU_RA6M5/object_oriented_module_programming_method_in_ARM_embedded_system/chapter5.md',
          '/zh/DShanMCU_RA6M5/object_oriented_module_programming_method_in_ARM_embedded_system/chapter6.md',
          '/zh/DShanMCU_RA6M5/object_oriented_module_programming_method_in_ARM_embedded_system/chapter7.md',
          '/zh/DShanMCU_RA6M5/object_oriented_module_programming_method_in_ARM_embedded_system/chapter8.md',
          '/zh/DShanMCU_RA6M5/object_oriented_module_programming_method_in_ARM_embedded_system/chapter9.md',
          '/zh/DShanMCU_RA6M5/object_oriented_module_programming_method_in_ARM_embedded_system/chapter10.md',
          '/zh/DShanMCU_RA6M5/object_oriented_module_programming_method_in_ARM_embedded_system/chapter11.md',
          '/zh/DShanMCU_RA6M5/object_oriented_module_programming_method_in_ARM_embedded_system/chapter12.md',
          '/zh/DShanMCU_RA6M5/object_oriented_module_programming_method_in_ARM_embedded_system/chapter13.md',
          '/zh/DShanMCU_RA6M5/object_oriented_module_programming_method_in_ARM_embedded_system/chapter14.md',
          '/zh/DShanMCU_RA6M5/object_oriented_module_programming_method_in_ARM_embedded_system/chapter15.md',
          '/zh/DShanMCU_RA6M5/object_oriented_module_programming_method_in_ARM_embedded_system/chapter16.md',
          '/zh/DShanMCU_RA6M5/object_oriented_module_programming_method_in_ARM_embedded_system/chapter17.md',
          '/zh/DShanMCU_RA6M5/object_oriented_module_programming_method_in_ARM_embedded_system/chapter18.md',
          '/zh/DShanMCU_RA6M5/object_oriented_module_programming_method_in_ARM_embedded_system/chapter19.md',
          '/zh/DShanMCU_RA6M5/object_oriented_module_programming_method_in_ARM_embedded_system/chapter20.md',
          '/zh/DShanMCU_RA6M5/object_oriented_module_programming_method_in_ARM_embedded_system/chapter21.md',
          '/zh/DShanMCU_RA6M5/object_oriented_module_programming_method_in_ARM_embedded_system/chapter22.md',
          '/zh/DShanMCU_RA6M5/object_oriented_module_programming_method_in_ARM_embedded_system/chapter23.md',
          '/zh/DShanMCU_RA6M5/object_oriented_module_programming_method_in_ARM_embedded_system/chapter24.md',
          '/zh/DShanMCU_RA6M5/object_oriented_module_programming_method_in_ARM_embedded_system/chapter25.md',
          '/zh/DShanMCU_RA6M5/object_oriented_module_programming_method_in_ARM_embedded_system/chapter26.md',
          '/zh/DShanMCU_RA6M5/object_oriented_module_programming_method_in_ARM_embedded_system/chapter27.md',
          '/zh/DShanMCU_RA6M5/object_oriented_module_programming_method_in_ARM_embedded_system/chapter28.md',
          '/zh/DShanMCU_RA6M5/object_oriented_module_programming_method_in_ARM_embedded_system/chapter29.md',
          '/zh/DShanMCU_RA6M5/object_oriented_module_programming_method_in_ARM_embedded_system/chapter30.md',
          '/zh/DShanMCU_RA6M5/object_oriented_module_programming_method_in_ARM_embedded_system/chapter31.md',
          '/zh/DShanMCU_RA6M5/object_oriented_module_programming_method_in_ARM_embedded_system/chapter32.md',
          '/zh/DShanMCU_RA6M5/object_oriented_module_programming_method_in_ARM_embedded_system/chapter33.md',
          '/zh/DShanMCU_RA6M5/object_oriented_module_programming_method_in_ARM_embedded_system/chapter34.md',
          '/zh/DShanMCU_RA6M5/object_oriented_module_programming_method_in_ARM_embedded_system/chapter35.md',
          '/zh/DShanMCU_RA6M5/object_oriented_module_programming_method_in_ARM_embedded_system/chapter36.md',
          '/zh/DShanMCU_RA6M5/object_oriented_module_programming_method_in_ARM_embedded_system/chapter37.md',
          '/zh/DShanMCU_RA6M5/object_oriented_module_programming_method_in_ARM_embedded_system/chapter38.md',
        ],
      },
    ],
  '/zh/DShanMCU_RA6M5/e2studio_use_dap/': [
    {
      text: '在e2studio中使用DAP进行开发调试',
      collapsible: true,
      children: [
        '/zh/DShanMCU_RA6M5/e2studio_use_dap/README.md',
        '/zh/DShanMCU_RA6M5/e2studio_use_dap/chapter1.md',
        '/zh/DShanMCU_RA6M5/e2studio_use_dap/chapter2.md',
        '/zh/DShanMCU_RA6M5/e2studio_use_dap/chapter3.md',
        '/zh/DShanMCU_RA6M5/e2studio_use_dap/chapter4.md',
        '/zh/DShanMCU_RA6M5/e2studio_use_dap/chapter5.md',
        '/zh/DShanMCU_RA6M5/e2studio_use_dap/chapter6.md',
        '/zh/DShanMCU_RA6M5/e2studio_use_dap/chapter7.md',
      ],
    },
  ],
  '/zh/DShanMCU_RA6M5/lvgl_port_special_tutorial/': [
    {
      text: 'LVGL移植专题',
      collapsible: true,
      children: [
        '/zh/DShanMCU_RA6M5/lvgl_port_special_tutorial/README.md',
        '/zh/DShanMCU_RA6M5/lvgl_port_special_tutorial/chapter1.md',
        '/zh/DShanMCU_RA6M5/lvgl_port_special_tutorial/chapter2.md',
        '/zh/DShanMCU_RA6M5/lvgl_port_special_tutorial/chapter3.md',
        '/zh/DShanMCU_RA6M5/lvgl_port_special_tutorial/chapter4.md',
        '/zh/DShanMCU_RA6M5/lvgl_port_special_tutorial/chapter5.md',
        '/zh/DShanMCU_RA6M5/lvgl_port_special_tutorial/chapter6.md',
        '/zh/DShanMCU_RA6M5/lvgl_port_special_tutorial/chapter7.md',
        '/zh/DShanMCU_RA6M5/lvgl_port_special_tutorial/chapter8.md',
        '/zh/DShanMCU_RA6M5/lvgl_port_special_tutorial/chapter9.md',
      ],
    },
  ],
  '/zh/DShanMCU_RA6M5/FreeRTOS': [
    {
      text: 'FreeRTOS入门与工程实践',
      collapsible: true,
      children: [
        '/zh/DShanMCU_RA6M5/lvgl_port_special_tutorial/README.md',
        '/zh/DShanMCU_RA6M5/lvgl_port_special_tutorial/chapter9.md',
        '/zh/DShanMCU_RA6M5/lvgl_port_special_tutorial/chapter10.md',
        '/zh/DShanMCU_RA6M5/lvgl_port_special_tutorial/chapter11.md',
      ],
    },
  ],
}
